// <auto-generated />
using System;
using Gamana_Muttopalvelu_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gamana_Muttopalvelu_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831180728_AdminTabless")]
    partial class AdminTabless
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("boolean");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("OfferId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeCleaning")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SelectedPackageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.CustomerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("customer_reviews", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.CustomerReviewTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateDisplay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("customer_review_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("detailed_services", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedServiceHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DetailedServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetailedServiceId");

                    b.ToTable("detailed_service_highlights", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedServiceHighlightTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HighlightId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HighlightId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("detailed_service_highlight_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedServiceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DetailedServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetailedServiceId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("detailed_service_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.FormServiceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("form_service_options", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.FormServiceOptionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OptionId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("form_service_option_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.KeyService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("key_services", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.KeyServiceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KeyServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyServiceId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("key_service_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DesiredMovingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrivacyAgreed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("pricing_packages", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackageFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("PricingPackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PricingPackageId");

                    b.ToTable("pricing_package_features", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackageFeatureTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("pricing_package_feature_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackageTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceDisplay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PricingPackageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PricingPackageId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("pricing_package_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.ProcessStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StepNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("process_steps", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.ProcessStepTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessStepId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("process_step_translations", (string)null);
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.RequestedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("RequestedServices");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Address", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.Booking", "Booking")
                        .WithMany("Addresses")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.Offer", "Offer")
                        .WithMany("Addresses")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Booking");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Booking", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.CustomerReviewTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.CustomerReview", "Review")
                        .WithMany("Translations")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedServiceHighlight", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.DetailedService", "DetailedService")
                        .WithMany("Highlights")
                        .HasForeignKey("DetailedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailedService");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedServiceHighlightTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.DetailedServiceHighlight", "Highlight")
                        .WithMany("Translations")
                        .HasForeignKey("HighlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Highlight");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedServiceTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.DetailedService", "DetailedService")
                        .WithMany("Translations")
                        .HasForeignKey("DetailedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailedService");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.FormServiceOptionTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.FormServiceOption", "Option")
                        .WithMany("Translations")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.KeyServiceTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.KeyService", "KeyService")
                        .WithMany("Translations")
                        .HasForeignKey("KeyServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyService");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Offer", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.User", "User")
                        .WithMany("Offers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackageFeature", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.PricingPackage", "PricingPackage")
                        .WithMany("Features")
                        .HasForeignKey("PricingPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingPackage");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackageFeatureTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.PricingPackageFeature", "Feature")
                        .WithMany("Translations")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackageTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.PricingPackage", "PricingPackage")
                        .WithMany("Translations")
                        .HasForeignKey("PricingPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingPackage");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.ProcessStepTranslation", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.ProcessStep", "ProcessStep")
                        .WithMany("Translations")
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.RequestedService", b =>
                {
                    b.HasOne("Gamana_Muttopalvelu_Backend.Data.Offer", "Offer")
                        .WithMany("RequestedServices")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Booking", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.CustomerReview", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedService", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.DetailedServiceHighlight", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.FormServiceOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.KeyService", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.Offer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("RequestedServices");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackage", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.PricingPackageFeature", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.ProcessStep", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Gamana_Muttopalvelu_Backend.Data.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
